version: '3.5'
services:
  zoo1:
    image: zookeeper:latest
    expose:
      - "2181"
      - "2888"
      - "3888"
    environment:
      ZOO_MY_ID: "1"
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - clickhouse-network

  zoo2:
    image: zookeeper:latest
    expose:
      - "2181"
      - "2888"
      - "3888"
    environment:
      ZOO_MY_ID: "2"
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    networks:
      - clickhouse-network

  zoo3:
    image: zookeeper:latest
    expose:
      - "2181"
      - "2888"
      - "3888"
    environment:
      ZOO_MY_ID: "3"
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    networks:
      - clickhouse-network

  clickhouse01:
    image: yandex/clickhouse-server:21.5
    container_name: clickhouse01
    hostname: clickhouse01
    networks:
      - clickhouse-network
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9001:9000"
    volumes:
      - ${PWD}/clickhouse01:/etc/clickhouse-server
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  clickhouse02:
    image: yandex/clickhouse-server:21.5
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      - clickhouse-network
    volumes:
      - ${PWD}/clickhouse02:/etc/clickhouse-server
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  clickhouse03:
    image: yandex/clickhouse-server:21.5
    container_name: clickhouse03
    hostname: clickhouse03
    networks:
      - clickhouse-network
    volumes:
      - ${PWD}/clickhouse03:/etc/clickhouse-server
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  clickhouse04:
    image: yandex/clickhouse-server:21.5
    container_name: clickhouse04
    hostname: clickhouse04
    networks:
      - clickhouse-network
    volumes:
      - ${PWD}/clickhouse04:/etc/clickhouse-server
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  clickhouse05:
    image: yandex/clickhouse-server:21.5
    container_name: clickhouse05
    hostname: clickhouse05
    networks:
      - clickhouse-network
    volumes:
      - ${PWD}/clickhouse03:/etc/clickhouse-server
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  clickhouse06:
    image: yandex/clickhouse-server:21.5
    container_name: clickhouse06
    hostname: clickhouse06
    networks:
      - clickhouse-network
    volumes:
      - ${PWD}/clickhouse04:/etc/clickhouse-server
    depends_on:
      - zoo1
      - zoo2
      - zoo3

networks:
  clickhouse-network:
    external:
      name: dev_network

